version: '3.8'
services:
    api:
        container_name: test-nestjs
        build:
            context: .
            target: development
            dockerfile: ./Dockerfile
        command: npm run start:dev
        depends_on:
            - db
        ports:
            - 3000:3000
            - 9229:9229
        networks:
            - nesjs-network
        env_file:
            - '.env'
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped
    db:
        image: postgres:12.1-alpine
        volumes:
            - ./db:/var/lib/postgresql/data
        #- ./db:/usr/local/pgsql/data
        ports: 
            - "5432:5432"
        networks:
            - nesjs-network
        env_file:
            - '.env'
networks:
    nesjs-network:
